raw : raw_data
lib_desc : Info-Tag-GBS_Filaire_HiSeq_290615-1.csv

name : v1

process_radtag_options : -c -q -r -D --renz_1 pstI --renz_2 mseI --inline_inline 

#   c,--clean: clean data, remove any read with an uncalled base.
#   q,--quality: discard reads with low quality scores.
#   r,--rescue: rescue barcodes and RAD-Tags.
#   D: capture discarded reads to a file.
#   --filter-illumina: discard reads that have been marked by Illumina's chastity/purity filter as failing.
#   --disable-rad-check: disable checking if the RAD site is intact.
#   --len-limit <limit>: specify a minimum sequence length (useful if your data has already been trimmed).
#   --barcode-dist-1: the number of allowed mismatches when rescuing single-end barcodes (default 1).
#   --barcode-dist-2: the number of allowed mismatches when rescuing paired-end barcodes (defaults to --barcode-dist-1).

top_dir : NO_BACKUP
sample_dir : samples
pairs_dir : samples_pairs
barcodes_dir : barcodes
lib_dir : lib
log_dir : log

sample_file : samples.txt
progeny_file : progeny.txt
lib_file : lib.txt
summary : summary
